// <auto-generated />
namespace LicentaStuff.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifProject));
        
        string IMigrationMetadata.Id
        {
            get { return "202006231558446_ModifProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
